findjob/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('job.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

job/urls.py
from django.urls import path
from . import views

app_name = 'job'

urlpatterns = [
   path('projects/<str:project_id>', views.projects, name='projects'),
   path('education', views.education, name='education'),
   path('', views.main, name='main'),
]

job/models.py
from django.db import models

# Create your models here.

job/views.py
from django.shortcuts import render


def main(request):
    return render(request, 'job/main.html')


def projects(request, project_id):
    return render(request, f'job/projects/{project_id}.html')


def education(request):
    return render(request, 'job/education.html')

job/templates/job/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="{% static '/job/css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static '/job/css/job.css' %}" rel="stylesheet" >
<script src="{% static '/job/js/bootstrap.min.js' %}" ></script>
</head>
<body>
    <div id="language-switch" class="btn-group">
      <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        {{ LANGUAGE_CODE }}
      </button>
      <ul class="dropdown-menu">
        {% for language in languages %}
        <li><a href="/{{ language.code }}{% block path %}{% endblock %}" class="dropdown-item">{{ language.name_local }}</a></li>
        {% endfor %}
      </ul>
    </div>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-1 col-md-3"></div>
            <div class="col-sm-10 col-md-6 p-4 d-flex flex-column align-items-center">
              {% block content %}
              {% endblock %}
            </div>
          <div class="col-sm-1 col-md-3"></div>
      </div>
    </div>  

    {% block js %}
    {% endblock %}
</body>
</html>

job/templates/job/contacts.html
{% load i18n %}
{% load static %}

<div class="d-flex flex-column align-self-center">
  <a class="mb-1" href="https://t.me/Tititun"><img class="me-1" height="25" src="{% static '/job/images/telegram.jpeg' %}">{% trans "Telegram" %}</a>
  <a class="mb-1" href="mailto:vinniopo@mail.ru"><img class="me-1" height="25" src="{% static '/job/images/mail.png' %}">{% trans "Email" %}</a>
  <a href="https://wa.me/79131110962"><img class="me-1" height="25" src="{% static '/job/images/whatsapp.jpeg' %}">Whatsapp</a>
</div>

job/templates/job/education.html
{% extends 'job/base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
{% trans "Education & Experience" %}
{% endblock %}

{% block path %}/education{% endblock %}

{% block content %}
  <a class="btn btn-link me-auto" type="button" href="{% url "job:main" %}">
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="bi bi-arrow-left fs-3" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
    </svg>
  </a>
  <h3 class="mb-3">{% trans "My Education and Experience" %}</h3>
  <p>
    {% trans "I'm currently studying at Moscow Witte University, my educational program is Applied computer science, and I'll graduate in 2025." %}
  </p>
  <p>  
    {% trans "I started my path in IT in 2020 when I decided to learn Python. Later I became interested in web-development - HTML, CSS and JavaScript. My first projects were web-scrapers, and I worked on several projects for clients from freelancer.com and youdo.com." %}
  </p>
  <p class="align-self-start">
    {% trans "I participated in two serious projects since 2020:" %}
  </p>
    <ul>
      <li>{% trans "My first serious job in IT was for <a href='https://www.econdb.com/'>econdb.com</a> - a data service for economic indicators. I've been working on web-scrapers and data analytics tools for this company since 2021. " %}</li>
      <li>{% trans "In 2022 I worked for a year on <a href='https://www.qarmatechnology.com/'>qarmatechnology project</a> - a company that implements Artificial Intelligence in stocks trading. My area of expertise was Django backend development." %}</li>
    </ul>
  <p>
    {% trans "My first education is a medical biochemistry bachelor's degree. I graduated from Siberian State Medical University in 2013 and worked in two hospitals in clinical laboratories between 2013 and 2020. In 2020 I decided to switch to programing and I love it ever since." %}
  </p> 
  <p>
    {% trans "In 2017 I passed IELTS exam with an average band of 8.0. I use English in my everyday life, I read programing literature , watch tutorials, read documentation in English." %}
    {% trans "My favorite directions in programing - data-analysis, web-development, machine learning (I don't have much experience in the latter though)." %}
  </p>
  <p>
    {% trans "I am looking for a beginner-level job. I can work remotely or move to the place of work at any time." %}
    {% trans "If you have any suggestions for me, I would be glad to hear of it! Please contact me:" %}
  </p>
  {% include "job/contacts.html" %}
{% endblock %}

job/templates/job/main.html
{% extends 'job/base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
{% trans "Job for Danil" %}
{% endblock %}

{% block path %}/{% endblock %}

{% block content %}
    <h3 class="mb-3">{% trans "Danil is looking for a job" %}</h3>
    <div class="d-flex flex-column">
        <p>
            {% trans "Hi! My name is Danil, and I'm looking for a job in the IT world." %}
        </p>
        <p>{% trans "My professional skills include:" %}</p>
        <ul>
            <li class="mb-1">{% trans "Programing languages - Python, JavaScript" %}</li>
            <li class="mb-1">{% trans "Web technologies - HTML, CSS" %}</li>
            <li class="mb-1">{% trans "SQL - CRUD-operations, window queries, joins etc." %}</li>
            <li class="mb-1">{% trans "Docker - container management, writing dockerfiles, docker-compose" %}</li>
            <li class="mb-1">{% trans "Git - all the basic operations" %}</li>
            <li class="mb-1">{% trans "English - I scored 8.0 in IELTS exam." %}</li>
        </ul>
        <p>{% trans "Python libraries I have most experience with:" %}</p>
        <ul>
            <li class="mb-1">{% trans "Data handling - pandas, numpy, matplotlib" %}</li>
            <li class="mb-1">{% trans "Web backend - Django" %}</li>
            <li class="mb-1">{% trans "Web scraping - requests, selenium, beautifulsoup" %}</li>
            <li class="mb-1">{% trans "Desktop applications - PyQT" %}</li>
        </ul>
        <p>{% trans "Apart from that I'm highly interested in machine learning and have some experience with tensorflow, pytorch and transformers." %}<br>
        {% trans "My most recent pet projects that I have on " %}<a href="https://github.com/Tititun?tab=repositories"><img class="me-1" height="25" src="{% static '/job/images/github.png' %}">{% trans "my GitHub page" %}</a>:</p>
        <ul>
            <li class="mb-1">
                <a href="{% url "job:projects" "vocabulary_builder" %}">Vocabulary builder</a> - {% trans "a project to organize vocabulary cards from your Kindle." %}
            </li>
            <li class="mb-1">
                <a href="{% url "job:projects" "job_search" %}">{% trans "This simple website" %}</a> - {% trans "a basic website built with Django." %}
            </li>
            <li class="mb-1">
                <a href="{% url "job:projects" "image_classification" %}">{% trans "Image classification project" %}</a> - {% trans "my little" %} <a href="{% url "job:education" %}">{% trans "university" %}</a>{% trans " project for image classification, built with tensorflow." %}
            </li>
            <li class="mb-1">
                <a href="{% url "job:projects" "nlp_experiment" %}">{% trans "My NLP experiment" %}</a> - {% trans "my modest attempt at multilingual classification of supermarket products." %}
            </li>
        </ul>
        <p>{% trans "Apart from that I have much experience in web-scraping, and also built a couple of Telegram bots." %}<br>
        {% trans "You can read more on my education and previous experience " %}<a href="{% url "job:education" %}">{% trans "here" %}</a></p>
        <p>{% trans "If you have any job you can offer me, please contact me:" %}</p>
        {% include "job/contacts.html" %}
    </div>

{% endblock %}

job/templates/job/projects/image_classification.html
{% extends 'job/projects/projects_base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
{% trans "Image classification" %}
{% endblock %}

{% block path %}
/projects/image_classification
{% endblock %}

{% block project_title %}
  {% trans "Image classification project" %}
{% endblock %}

{% block project_content %}
  <p>
    <a class="mb-1" href="https://github.com/Tititun/image_classification"><img class="me-1" height="25" src="{% static '/job/images/github.png' %}"></a>
    {% trans "The project was made for my practice at University where I'm currently studying. It was a machine learning task, where I needed to classify supermarket product images into 40 categories. For this purpose I used the following:" %}
    <ul>
      <li>{% trans "Data analysis tools: pandas, numpy, matplotlib" %}</li>
      <li>{% trans "Machine learning libraries: tensorflow, scikit-learn" %}</li>
      <li>{% trans "Jupyter notebooks for my work presentation" %}</li>
      <li>{% trans "Web scraping to collect the images from more than 50 supermarkets worldwide - requests, beautifulsoup, selenium" %}</li>
    </ul>
  </p>
  <p>
    {% trans "For solving the image classification problem I used deep convoluted networks as well as transfer learning. After training eight models I chose the best of them and combined them using ensemble methods." %}<br>
    {% trans "The resulting accuracy was 85%. The example of images is shown below:" %}
  </p>
  <img class="example-image" src="{% static "job/images/image_classification.png" %}">
{% endblock %}

job/templates/job/projects/job_search.html
{% extends 'job/projects/projects_base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
{% trans "Job search website" %}
{% endblock %}

{% block path %}
/projects/job_search
{% endblock %}

{% block project_title %}
{% trans "This (job search) website" %}
{% endblock %}

{% block project_content %}
  <p>
    <a class="mb-1" href="https://github.com/Tititun/findjob"><img class="me-1" height="25" src="{% static '/job/images/github.png' %}"></a>
    {% trans "This basic website uses bare minimum of:" %}
    <ul>
      <li>Backend - Django</li>
      <li>Web: HTML, CSS ({% trans "primarily, Bootstrap library" %})</li>
      <li>{% trans "Database: MySQL" %}</li>
    </ul>
  </p>
  <p>
    {% trans "The feature that distinguishes this simple website is the use of two languages - English and Russian. For this purpose I used Django's Internationalization capabilities. Each page is translated with trans-tags of Django templating language. User can switch the language by using the language switch in the top-right corner." %}
  </p>
  <img class="w-50 align-self-center mt-3" src="{% static "job/images/job_search.png" %}">
{% endblock %}

job/templates/job/projects/nlp_experiment.html
{% extends 'job/projects/projects_base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
{% trans "NLP experiment" %}
{% endblock %}

{% block path %}
/projects/nlp_experiment
{% endblock %}

{% block project_title %}
{% trans "NLP experiment" %}
{% endblock %}

{% block project_content %}
  <p>
    <a class="mb-1" href="https://github.com/Tititun/data_cleaner"><img class="me-1" height="25" src="{% static '/job/images/github.png' %}"></a>
    {% trans "This ongoing project is an attempt to build a NLP classifier for supermarket products using their title. The following techologies have been used:" %}
    <ul>
      <li>Backend - Django, Django REST framework</li>
      <li>Fronend - React, HTML, CSS (Bulma)</li>
      <li>{% trans "Machine learning: Pytorch, transformers, scikit-learn" %}</li>
      <li>{% trans "Data handling - pandas, matplotlib" %}</li>
    </ul>
  </p>
  <p>
    {% trans "The main difficulty of the project is that the data consists of more than 20 languages, so the main component of the classifier is XLMRoberta model - the famous multilingual model trained on more than 100 languages. I fine-tuned this model for the task at hand. I plan to add image, brand and weight/volume information to my ensemble model to achieve better results." %}<br>
    {% trans "An important part of this project is a data cleaner tool which is used for filtering, cleaning and labeling the data. This is a web tool built with Django. Its interface is shown on the picture below:" %}
  </p>
  <img class="example-image" src="{% static "job/images/nlp_experiment.png" %}">
{% endblock %}

job/templates/job/projects/projects_base.html
{% extends 'job/base.html' %}
{% load static %}

{% block content %}
  <a class="btn btn-link me-auto" type="button" href="{% url "job:main" %}">
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="bi bi-arrow-left fs-3" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
    </svg>
  </a>
  <h3 class="mb-3">
    {% block project_title %}
    {% endblock %}
  </h3>
  <div class="d-flex flex-column">
    {% block project_content %}
    {% endblock %}
  </div>
{% endblock %}

job/templates/job/projects/vocabulary_builder.html
{% extends 'job/projects/projects_base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
Vocabulary builder
{% endblock %}

{% block path %}
/projects/vocabulary_builder
{% endblock %}

{% block project_title %}
  Vocabulary builder
{% endblock %}

{% block project_content %}
  <p>
    <a class="mb-1" href="https://github.com/Tititun/vocbuilder"><img class="me-1" height="25" src="{% static '/job/images/github.png' %}"></a>
    {% trans "This website is located at " %}
    <a href="https://vocab-cards.online/">vocab-cards.online</a>
    {% trans "is built with the following techologies:" %}
    <ul>
      <li>Python - Django</li>
      <li>JavaScript - React</li>
      <li>Web: HTML, CSS ({% trans "primarily, Bootstrap library" %})</li>
      <li>{% trans "Database: MySQL" %}</li>
      <li>{% trans "Deployment: Docker, docker-compose" %}</li>
    </ul>
  </p>
  <p>
    {% trans "It is a simple website that is designed to extract vocabulary from a Kindle device. The tutorial is located at " %}
    <a href="https://vocab-cards.online/about">How it works</a>.<br>
    {% trans "It uses web scraping to fetch definitions from online dictionaries and present the results in a convinient form of cards, with an option to download the data in csv/tsv formats." %}
    <br>
    {% trans "Obviously, there is a space for improvements: I plan to add telegram bot for queezes, add more languages, add social media links etc." %}
  </p>
  <img class="example-image" src="{% static "job/images/vocab_cards.png" %}">
{% endblock %}